services:
  - type: worker
    name: sage-otp-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_DB_URL
        sync: false
      - key: ACCHUB_EMAIL
        sync: false
      - key: ACCHUB_PASSWORD
        sync: false
      - key: BOT_NAME
        value: SAGE OTP